name: check-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: using docker for qemu
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: create directory
      run: mkdir -p build/bin && chmod -R 777 ./ 
    - name: make for arm
      run: docker run --rm -v $(pwd):/workdir ivan28823/emcaworkspace
